### model
model_name_or_path: ../Qwen/Qwen2.5-32B-Instruct
adapter_name_or_path: saves/Qwen2.5-32B-Instructs/lora/sft_fast12
trust_remote_code: true

### method
finetuning_type: lora

### dataset
task: mmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: en
n_shot: 5

### output
save_dir: saves/Qwen2.5-32B/lora/eval

### eval
batch_size: 4
